### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by enzzodani** [Gigas002/hyprdots-sweet#1]
![image](https://github.com/Gigas002/hyprdots-sweet/assets/135847182/75926741-8782-48ad-9d50-948cf9d416f1)

**Comment by Gigas002** [comment]
Should be fixed with https://github.com/Gigas002/hyprdots-sweet/commit/18b8648630608da42c778e75e34dd3fea5df1d6a. Feel free to reopen the issue if anything else is borked
